services:
  postgres-member:
    image: postgres:16-alpine
    container_name: postgres-member
    environment:
      POSTGRES_DB: memberdb
      POSTGRES_USER: member_user
      POSTGRES_PASSWORD: member_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-member-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U member_user -d memberdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-member-data:
